# coding: utf-8

"""
    Clinical Match API

    A simple API to match patients to clinical trials.

    The version of the OpenAPI document: 1.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_clinicalmatch_post_request_location import V1ClinicalmatchPostRequestLocation

class TestV1ClinicalmatchPostRequestLocation(unittest.TestCase):
    """V1ClinicalmatchPostRequestLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ClinicalmatchPostRequestLocation:
        """Test V1ClinicalmatchPostRequestLocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ClinicalmatchPostRequestLocation`
        """
        model = V1ClinicalmatchPostRequestLocation()
        if include_optional:
            return V1ClinicalmatchPostRequestLocation(
                latitude = 42.349806,
                longitude = -71.06149
            )
        else:
            return V1ClinicalmatchPostRequestLocation(
                latitude = 42.349806,
                longitude = -71.06149,
        )
        """

    def testV1ClinicalmatchPostRequestLocation(self):
        """Test V1ClinicalmatchPostRequestLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
