# coding: utf-8

"""
    Clinical Match API

    A simple API to match patients to clinical trials.

    The version of the OpenAPI document: 1.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_v1_clinicalmatch_post(self) -> None:
        """Test case for v1_clinicalmatch_post

        Submit patient notes for clinical trial matching
        """
        pass

    def test_version_get(self) -> None:
        """Test case for version_get

        Get API version
        """
        pass


if __name__ == '__main__':
    unittest.main()
