# coding: utf-8

"""
    Clinical Match API

    A simple API to match patients to clinical trials.

    The version of the OpenAPI document: 1.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_clinicalmatch_post400_response import V1ClinicalmatchPost400Response

class TestV1ClinicalmatchPost400Response(unittest.TestCase):
    """V1ClinicalmatchPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ClinicalmatchPost400Response:
        """Test V1ClinicalmatchPost400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ClinicalmatchPost400Response`
        """
        model = V1ClinicalmatchPost400Response()
        if include_optional:
            return V1ClinicalmatchPost400Response(
                status = 'error',
                message = 'File size does not match the specified byte count.'
            )
        else:
            return V1ClinicalmatchPost400Response(
        )
        """

    def testV1ClinicalmatchPost400Response(self):
        """Test V1ClinicalmatchPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
