# coding: utf-8

"""
    Clinical Match API

    A simple API to match patients to clinical trials.

    The version of the OpenAPI document: 1.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.version_get200_response import VersionGet200Response

class TestVersionGet200Response(unittest.TestCase):
    """VersionGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionGet200Response:
        """Test VersionGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionGet200Response`
        """
        model = VersionGet200Response()
        if include_optional:
            return VersionGet200Response(
                version = '1.0.0'
            )
        else:
            return VersionGet200Response(
        )
        """

    def testVersionGet200Response(self):
        """Test VersionGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
